2022-10-07 15:25:01,310 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:25:09,225 ERROR: Exception on /comments/1 [GET] [in c:\users\bbird\diary\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\bbird\diary\app\main\routes.py", line 127, in comments
    return render_template("comments.html",title="My Diary",post=post)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bbird\diary\app\templates\comments.html", line 1, in top-level template code
    {% extends "layouts/base.html" %}
  File "C:\Users\bbird\diary\app\templates\layouts\base.html", line 144, in top-level template code
    {% block content %} {% endblock %}
  File "C:\Users\bbird\diary\app\templates\comments.html", line 17, in block 'content'
    {{form.hidden_tag()}}
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-10-07 15:34:33,849 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:34:40,946 ERROR: Exception on /comments/1 [GET] [in c:\users\bbird\diary\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\bbird\diary\app\main\routes.py", line 127, in comments
    return render_template("comments.html",title="My Diary",post=post)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bbird\diary\app\templates\comments.html", line 1, in top-level template code
    {% extends "layouts/base.html" %}
  File "C:\Users\bbird\diary\app\templates\layouts\base.html", line 144, in top-level template code
    {% block content %} {% endblock %}
  File "C:\Users\bbird\diary\app\templates\comments.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "c:\users\bbird\diary\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-10-07 15:35:08,439 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:36:55,184 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:40:48,660 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:41:45,456 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:42:49,654 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:44:15,615 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:45:53,559 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:45:56,954 ERROR: Exception on /comments/1 [POST] [in c:\users\bbird\diary\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\bbird\diary\app\main\routes.py", line 126, in comments
    print(f'time {c.timestamp}')
NameError: name 'c' is not defined
2022-10-07 15:46:20,351 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 15:47:40,570 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 16:28:13,342 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 16:28:18,006 ERROR: Exception on /comments/1 [POST] [in c:\users\bbird\diary\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bbird\diary\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\bbird\diary\app\main\routes.py", line 136, in comments
    comment=comment)
UnboundLocalError: local variable 'comment' referenced before assignment
2022-10-07 16:30:18,485 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
2022-10-07 16:45:18,420 INFO: PharmbookDiary startup [in C:\Users\bbird\diary\app\__init__.py:78]
